include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/app_icons.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_use_package_imports: true
    close_sinks: true
    literal_only_boolean_expressions: true
    avoid_returning_this: true
    always_put_control_body_on_new_line: true
    prefer_foreach: true
    prefer_single_quotes: true
    lowercase_with_underscores: true
    use_to_and_as_if_applicable: true
    use_named_constants: true
    use_is_even_rather_than_modulo: true
    use_if_null_to_convert_nulls_to_bools: true
    unawaited_futures: true
    prefer_null_aware_method_calls: true
    avoid_multiple_declarations_per_line: true
    avoid_double_and_int_checks: true
    always_put_required_named_parameters_first: true
    only_throw_errors: true
    cascade_invocations: true
    sort_pub_dependencies: false
    avoid_escaping_inner_quotes: false
    depend_on_referenced_packages: false
