name: vizier
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Localizations 
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  #Bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  #Code generation
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  #Dependency Injection
  injectable: ^1.5.3
  get_it: ^7.2.0
  #Storages
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15
  #Routing
  auto_route: ^5.0.1
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  circular_bottom_navigation: ^2.3.0
  firebase_core: ^2.13.0
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  flutter_datetime_picker: ^1.5.1





    #UI
  flutter_svg: ^1.1.4
  mrx_charts: ^0.1.3
  build_runner: ^2.0.7


dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  lint: ^1.10.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
    - assets/mocks/finances/
    - assets/mocks/user/
    - assets/mocks/portfolio/
    - assets/mocks/transactions/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
